CONFIG = {
    "canton": "BLBS",
    "excel_file": "BL_nais_einheiten_unique_v3_mf.xlsx",
    "excel_sheet": "Sheet1",
    "excel_format": "nais_hs",
    "join_keys": ["g1_txt", "waldgesell"],
    "shapefile": "BLBS/Standortskarte_fixed.gpkg",
    "raster_dem": "BLBS/BLBS_dem10m.tif",
    "raster_slope": "BLBS/BLBS_slopeprz.tif",
    "raster_radiation": "BLBS/BLBS_globradyyw.tif",
    "raster_hs": "BLBS/BLBS_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "extended",
    "filter_col": None,
    "treeapp_col_start": 25,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "g1_txt", "waldgesell", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "g1_txt", "waldgesell", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
