CONFIG = {
    "canton": "LU",
    "excel_file": "LU_nais_einheiten_unique_mf_Juli 2025.xlsx",
    "excel_sheet": None,
    "excel_format": "nais1_nais2_hs",
    "join_keys": ["PLOTTXT", "STO1_TXT", "STO2_TXT"],
    "shapefile": "geops_treeapp/forest_types_lu/forest_types_lu.shp",
    "raster_dem": "LU/LU_dem10m.tif",
    "raster_slope": "LU/LU_slopeprz.tif",
    "raster_radiation": "LU/LU_globradyyw.tif",
    "raster_hs": "LU/LU_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "standard",
    "filter_col": None,
    "treeapp_col_start": 27,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "PLOTTXT", "STO1_TXT", "STO2_TXT", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "PLOTTXT", "STO1_TXT", "STO2_TXT", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
