CONFIG = {
    "canton": "NE",
    "excel_file": "NE_nais_einheiten_unique_mf.xlsx",
    "excel_sheet": "export",
    "excel_format": "nais_hs",
    "join_keys": ["code_neuch", "code_nais"],
    "shapefile": "geops_treeapp/forest_types_ne/forest_types_ne.shp",
    "raster_dem": "NE/NE_dem10m.tif",
    "raster_slope": "NE/NE_slope10mprz.tif",
    "raster_radiation": "NE/NE_globradyw.tif",
    "raster_hs": "NE/NE_hs1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "standard",
    "filter_col": None,
    "treeapp_col_start": 27,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "code_neuch", "code_nais", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "code_neuch", "code_nais", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
