CONFIG = {
    "canton": "NW",
    "excel_file": "NW_nais_einheiten_unique_mf.xlsx",
    "excel_sheet": "Sheet1",
    "excel_format": "nais_hs",
    "join_keys": ["Beschriftu", "Art_1", "Art_2", "Art_Ueberg"],
    "shapefile": "NW/Waldgesellschaften_Ellenberg_Klötzli_1972.shp",
    "raster_dem": "NW/nw_dem10m.tif",
    "raster_slope": "NW/nw_slope10mprz.tif",
    "raster_radiation": "NW/nw_globradyw.tif",
    "raster_hs": "NW/nw_hs1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "standard",
    "filter_col": None,
    "treeapp_col_start": 27,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "Beschriftu", "Art_1", "Art_2", "Art_Ueberg",
        "taheute", "storeg", "meanslopeprc", "slpprzrec", "rad", "radiation",
        "hs1975", "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue",
        "geometry",
    ],
    "treeapp_cols": [
        "Beschriftu", "Art_1", "Art_2", "Art_Ueberg", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
