CONFIG = {
    "canton": "SH",
    "excel_file": "SH_nais_einheiten_unique_v3_mf_Juli2025.xlsx",
    "excel_sheet": None,
    "excel_format": "nais1_nais2_hs",
    "join_keys": ["wg_nr"],
    "shapefile": "SH/Waldstandortkarte_detailliert.shp",
    "raster_dem": "SH/SH_dem10m.tif",
    "raster_slope": "SH/SH_slopeprz.tif",
    "raster_radiation": "SH/SH_globradyyw.tif",
    "raster_hs": "SH/SH_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "standard",
    "filter_col": None,
    "treeapp_col_start": 25,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "wg_nr", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "wg_nr", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
