CONFIG = {
    "canton": "SZ",
    "excel_file": "SZ_nais_einheiten_unique_bh_20241128_mf_bh_mfJuli 2025.xlsx",
    "excel_sheet": "Sheet",
    "excel_format": "nais1_nais2_hs",
    "join_keys": ["SZ Einheit"],
    "shapefile": "SZ/SZ_standortstypen.gpkg",
    "raster_dem": "SZ/SZ_dem10m.tif",
    "raster_slope": "SZ/SZ_slopeprz.tif",
    "raster_radiation": "SZ/SZ_globradyyw_lv95.tif",
    "raster_hs": "SZ/SZ_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "overlay",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "extended",
    "filter_col": None,
    "treeapp_col_start": 25,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "SZ Einheit", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "SZ Einheit", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
