CONFIG = {
    "canton": "TG",
    "excel_file": "TG_nais_einheiten_unique_mf.xlsx",
    "excel_sheet": "Sheet1",
    "excel_format": "nais1_nais2_hs",
    "join_keys": ["TGneu", "NaiSalt"],
    "shapefile": "TG/StandortskarteNaiS_AbgabeKanton_20200709.shp",
    "raster_dem": "TG/TG_dem10m.tif",
    "raster_slope": "TG/TG_slopeprz.tif",
    "raster_radiation": "TG/TG_globradyyw.tif",
    "raster_hs": "TG/TG_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "sjoin",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "extended",
    "filter_col": None,
    "treeapp_col_start": 25,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "TGneu", "NaiSalt", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "TGneu", "NaiSalt", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
