CONFIG = {
    "canton": "ZG",
    "excel_file": "ZG_nais_einheiten_unique_v2_mf_v2.xlsx",
    "excel_sheet": "Sheet1",
    "excel_format": "nais1_nais2_hs",
    "join_keys": ["NUMMER", "Beschriftu"],
    "shapefile": "ZG/ZG_kartierung_merge.gpkg",
    "raster_dem": "ZG/ZG_dem10m.tif",
    "raster_slope": "ZG/ZG_slopeprz.tif",
    "raster_radiation": "ZG/ZG_globradyyw.tif",
    "raster_hs": "ZG/ZG_vegetationshoehenstufen1975.tif",
    "taheute_file": "Tannenareale.shp",
    "taheute_method": "overlay",
    "storeg_file": "Waldstandortsregionen.shp",
    "storeg_method": "sjoin",
    "radiation_method": "quantile",
    "dict_variant": "extended",
    "filter_col": None,
    "treeapp_col_start": 25,
    "treeapp_col_end": -2,
    "custom_hook": False,
    "output_cols": [
        "joinid", "NUMMER", "Beschriftu", "taheute", "storeg",
        "meanslopeprc", "slpprzrec", "rad", "radiation", "hs1975",
        "nais", "nais1", "nais2", "mo", "ue", "hs", "tahs", "tahsue", "geometry",
    ],
    "treeapp_cols": [
        "NUMMER", "Beschriftu", "nais", "nais1", "nais2",
        "mo", "ue", "tahs", "tahsue", "geometry",
    ],
}
